import '@testing-library/jest-dom/vitest';
import {cleanup,render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,beforeEach,expect,test} from 'vitest';
import {App} from './App';
import {Provider} from 'react-redux';
import {clearSelection,setQuery,store} from './store';
const renderApp=()=>render(<Provider store={store}><App/></Provider>);
beforeEach(()=>{store.dispatch(clearSelection());store.dispatch(setQuery(''));localStorage.clear()});afterEach(()=>cleanup());
test('derives twelve active procedures and opens agriculture dossier',async()=>{const u=userEvent.setup();renderApp();expect(screen.getByText('Oportunităţi active').parentElement).toHaveTextContent('12');await u.click(screen.getByRole('button',{name:'Oportunități 12'}));await u.click(screen.getByRole('button',{name:/Furnizare legume/}));expect(screen.getByRole('heading',{name:/Furnizare legume/})).toBeInTheDocument();expect(screen.getAllByText(/03000000-1/).length).toBeGreaterThan(0)});
test('searches evidence and persists pipeline',async()=>{const u=userEvent.setup();renderApp();await u.click(screen.getByRole('button',{name:'Căutare în dovezi'}));await u.type(screen.getByRole('textbox',{name:'Caută în dovezi'}),'securitate');expect(screen.getByText('Caiet de sarcini')).toBeInTheDocument();await u.click(screen.getByRole('button',{name:'Dosarele mele'}));const s=screen.getByRole('combobox',{name:/Platformă IT pentru servicii digitale/});await u.selectOptions(s,'În pregătire');expect(JSON.parse(localStorage.getItem('tender-pipeline')||'{}')['SYN-RO-26-009']).toBe('În pregătire')});
