import { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { demoDetail, demoTenders } from './demoData';
import type { Detail, Tender } from './types';
import { clearSelection, closeEvidence, openEvidence, selectTender, setQuery, type AppDispatch, type RootState } from './store';

const money = (n:number) => new Intl.NumberFormat('ro-RO',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const isPages = typeof window !== 'undefined' && window.location.hostname.endsWith('github.io');
const labels:Record<string,string> = {identitate:'Identitate',calendar:'Calendar',buget:'Buget',criterii:'Criterii',documente:'Documente'};

export function App() {
  const dispatch = useDispatch<AppDispatch>();
  const { query, selectedTenderId, evidenceIndex } = useSelector((state: RootState) => state.dashboard);
  const [tenders,setTenders]=useState<Tender[]>([]); const [detail,setDetail]=useState<Detail|null>(null); const [mode,setMode]=useState<'local'|'static'>(isPages?'static':'local'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{ if(mode==='static'){setTenders(demoTenders);setLoading(false);return;} setLoading(true); fetch('/api/tenders').then(r=>{if(!r.ok)throw Error('API indisponibilă');return r.json()}).then(setTenders).catch(e=>setError(`Nu pot contacta API-ul local: ${e.message}`)).finally(()=>setLoading(false)); },[mode]);
  const filtered=useMemo(()=>tenders.filter(t=>`${t.id} ${t.title} ${t.buyer}`.toLowerCase().includes(query.toLowerCase())),[tenders,query]);
  useEffect(() => {
    const selected = tenders.find((tender) => tender.id === selectedTenderId);
    if (!selected) { setDetail(null); return; }
    if (mode === 'static') { setDetail(demoDetail(selected)); return; }
    fetch(`/api/tenders/${encodeURIComponent(selected.id)}`).then(r=>r.json()).then(setDetail).catch(()=>setError('Detaliul nu a putut fi încărcat.'));
  }, [mode, selectedTenderId, tenders]);
  const evidence = detail && evidenceIndex !== null ? detail.claim.evidence[evidenceIndex] : null;
  return <><header><div className="top"><div><span className="eyebrow">CLEAN-ROOM · DOAR DATE SINTETICE</span><h1>Tender <em>Intelligence</em></h1><p>Un cockpit calm pentru dosar, oferte și dovezi.</p></div><div className="mode" aria-label="Sursa datelor"><span className={mode==='local'?'live':''}></span>{mode==='local'?'API local':'Demo static'}<button onClick={()=>{setMode(mode==='local'?'static':'local');setError('');dispatch(clearSelection())}}>Schimbă</button></div></div></header><main><aside className="panel sidebar"><div className="section-title"><div><span className="eyebrow">DOSARE</span><h2>Licitații</h2></div><span className="count">{tenders.length}</span></div><label htmlFor="search">Caută în dosare</label><input id="search" value={query} onChange={e=>dispatch(setQuery(e.target.value))} placeholder="Titlu, cumpărător sau ID" />{loading?<div className="skeleton-list" aria-label="Se încarcă"/>:error&&!tenders.length?<div className="notice error">{error}</div>:filtered.length?<div className="tender-list">{filtered.map(t=><button className={`tender ${selectedTenderId===t.id?'selected':''}`} key={t.id} onClick={()=>dispatch(selectTender(t.id))}><span className="status-dot"></span><span><b>{t.title}</b><small>{t.buyer}</small></span><span className="arrow">→</span></button>)}</div>:<div className="empty"><strong>Niciun rezultat</strong><small>Încearcă un alt termen.</small></div>}</aside><section className="panel content">{error&&tenders.length>0&&<div className="notice error">{error}</div>}{!detail?<div className="welcome"><div className="compass">✦</div><span className="eyebrow">VIZIBILITATE PENTRU DECIZII</span><h2>Selectează un dosar</h2><p>Alege o licitație din stânga pentru a vedea completitudinea, comparația ofertelor și sursele verificabile.</p></div>:<DetailView detail={detail} onEvidence={(index)=>dispatch(openEvidence(index))}/>}</section></main>{evidence&&<div className="scrim" onClick={()=>dispatch(closeEvidence())}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>dispatch(closeEvidence())} aria-label="Închide">×</button><span className="eyebrow">DOVADĂ {detail?.claim.evidence_ids[evidenceIndex ?? 0]}</span><h2>{evidence.name}</h2><div className="source-card"><span>SURSĂ ALLOWLIST</span><code>{evidence.source}</code></div><div className="meta"><span><b>Pagină</b>{evidence.page}</span><span><b>Offset</b>{evidence.offset}</span></div><p>Fragment sintetic asociat acestui document. Într-un flux real, această zonă ar indica exact pasajul care susține afirmația.</p></aside></div>}</>;
}
function DetailView({detail,onEvidence}:{detail:Detail,onEvidence:(index:number)=>void}) { const {tender,dossier}=detail; return <><div className="detail-head"><div><span className="eyebrow">{tender.id}</span><h2>{tender.title}</h2><p>{tender.buyer} · termen {tender.deadline}</p></div><span className={`pill ${dossier.gate}`}>{dossier.gate==='ready'?'● Pregătit':'● Blocat'} {dossier.score}/{dossier.max_score}</span></div><div className="metrics"><div><small>Valoare estimată</small><strong>{money(tender.value_eur)}</strong></div><div><small>Oferte primite</small><strong>{detail.bids.length}</strong></div><div><small>Documente complete</small><strong>{detail.completeness.complete}/{detail.completeness.total}</strong></div></div><div className="section-title"><h3>Poarta dosarului</h3><span className="muted">5 criterii obligatorii</span></div><div className="checks">{Object.entries(dossier.checks).map(([key,ok])=><div className={ok?'check ok':'check'} key={key}><span>{ok?'✓':'!'}</span>{labels[key]}<small>{ok?'Validat':'Lipsește'}</small></div>)}</div><div className="section-title"><h3>Comparație oferte</h3><span className="muted">ordonate după preț</span></div>{detail.bids.length?<div className="bid-table"><div className="table-head"><span>Furnizor</span><span>Preț</span><span>Tehnic</span><span>Livrare</span></div>{detail.bids.map((b,i)=><div className="bid" key={b.firm}><span><i className="rank">{i+1}</i><b>{b.firm}</b></span><span>{money(b.price_eur)}</span><span>{b.technical}/100</span><span>{b.delivery_days} zile</span></div>)}</div>:<div className="notice">Nu există oferte în acest dosar demo.</div>}<div className="section-title claim-title"><h3>Afirmație citată</h3><span className="confidence">Încredere {detail.claim.confidence}</span></div><blockquote>“{detail.claim.claim}”<footer>{detail.claim.evidence_ids.map((id,i)=><button key={id} onClick={()=>onEvidence(i)}>{id}</button>)}</footer></blockquote><p className="uncertainty">ⓘ {detail.claim.uncertainty}</p></>; }
