import raw from '../shared/tenders.json';
import type { CPV, Conclusion, Detail, EntityResult, Tender } from './types';

type RawTender = typeof raw[number];
export const demoTenders: Tender[] = (raw as RawTender[]).map((x:any) => ({...x, buyerId:x.buyer_id, documents:x.docs.map((d:any)=>({name:d[0],complete:d[1],source:`fixture://${x.id.toLowerCase()}/${d[0].toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`,page:d[2],offset:d[2]*117,snippet:d[3]})), bids:x.bids.map((b:any)=>({firm:b[0],price_mdl:b[1],quality:b[2],delivery_days:b[3],status:b[4]}))}));
export const cpvDomains: CPV[] = [...new Map(demoTenders.map(t=>[t.cpv.code,t.cpv])).values()];
export const buyers = [...new Map(demoTenders.map(t=>[t.buyerId,{id:t.buyerId,name:t.buyer,pattern:`${demoTenders.filter(y=>y.buyerId===t.buyerId).length} proceduri în istoricul sintetic`}])).values()];
export const companies = [...new Set(demoTenders.flatMap(t=>t.bids.map(b=>b.firm)))].map((name,i)=>({id:`SUP-SYN-${String(i+1).padStart(3,'0')}`,name, wins:demoTenders.filter(t=>t.bids.some(b=>b.firm===name&&b.status==='Câştigătoare')).length,focus:[...new Set(demoTenders.filter(t=>t.bids.some(b=>b.firm===name)).map(t=>t.cpv.code))].join(', ')}));
export const detailFor=(t:Tender):Detail=>{const avg=t.bids.length?t.bids.reduce((a,b)=>a+b.price_mdl,0)/t.bids.length:t.value_mdl;const discount=Math.round((1-avg/t.value_mdl)*100);const source=t.documents[0]?.source||`fixture://${t.id.toLowerCase()}/dosar`;const conclusions:Conclusion[]=[{title:'Decizie explicabilă',text:`${t.decision}: potrivire ${t.fit}/100 şi risc ${t.risk}/100 în regula sintetică a dosarului.`,source,confidence:'Ridicată'},{title:'Presiune de preţ',text:t.bids.length?`Ofertele sunt în medie cu ${Math.max(0,discount)}% sub estimare.`:'Nu există oferte; presiunea de preţ nu poate fi estimată.',source,confidence:t.bids.length?'Medie':'Limitată'},{title:'Context de domeniu',text:`${t.cpv.name}. ${t.summary}`,source,confidence:'Medie'}];return {tender:t,checks:t.requirements.map((label,j)=>({label,value:j===0||t.documents.every(d=>d.complete),note:t.documents.every(d=>d.complete)?'Confirmat în documentul dosarului':'Necesită validare în dosarul furnizorului'})),evidence:t.documents,conclusions};};
export const searchEntities=():EntityResult[]=>[...demoTenders.flatMap(t=>[...t.documents.map(d=>({kind:'Dovadă' as const,title:d.name,subtitle:`${t.id} · ${t.cpv.code} · ${d.snippet}`,tenderId:t.id})),...detailFor(t).conclusions.map(c=>({kind:'Analiză' as const,title:c.title,subtitle:`${t.id} · ${t.cpv.code} · ${c.text}`,tenderId:t.id}))]),...demoTenders.map(t=>({kind:'Procedură' as const,title:t.title,subtitle:`${t.id} · ${t.cpv.code} · ${t.cpv.name} · ${t.buyer}`,tenderId:t.id})),...buyers.map(b=>({kind:'Cumpărător' as const,title:b.name,subtitle:`${b.id} · istoric sintetic`,entityType:'buyer' as const,entityId:b.id})),...companies.map(c=>({kind:'Companie' as const,title:c.name,subtitle:`${c.id} · CPV ${c.focus} · participări sintetice`,entityType:'company' as const,entityId:c.id}))];
