import type { CPV, Conclusion, Detail, EntityResult, Tender } from './types';

export const cpvDomains: CPV[] = [
 {code:'03000000-1',name:'Produse agricole, de fermă, de pescuit, de silvicultură şi produse conexe'},
 {code:'09000000-3',name:'Produse petroliere, combustibil, electricitate şi alte surse de energie'},
 {code:'15000000-8',name:'Alimente, băuturi, tutun şi produse conexe'},
 {code:'30190000-7',name:'Diverse maşini, echipamente şi accesorii de birou'},
 {code:'33100000-1',name:'Echipamente medicale'},
 {code:'33600000-6',name:'Produse farmaceutice'},
 {code:'45000000-7',name:'Lucrări de construcţii'},
 {code:'60000000-8',name:'Servicii de transport (cu excepţia transportului de deşeuri)'},
 {code:'72000000-5',name:'Servicii IT: consultanţă, dezvoltare de software, internet şi asistenţă'},
 {code:'79800000-2',name:'Servicii tipografice şi servicii conexe'},
 {code:'80500000-9',name:'Servicii de formare'},
 {code:'90910000-9',name:'Servicii de curăţenie'}
];
const buyersSeed=['Municipiul Exemplu','Universitatea Exemplu','Agenția Fictivă pentru Servicii','Consiliul Regional Exemplu','Spitalul Public Exemplu','Institutul Național Fictiv','Școala Exemplu','Centrul Medical Fictiv'];
const firms=['Nordic Byte Fictiv SRL','Cobalt Systems Exemplu SRL','Delta Atelier Fictiv SRL','Prut Labs Exemplu SRL','Carpatica Furnizor Fictiv SRL','Orizont Logistic Exemplu SRL','Mesteacăn Medical Fictiv SRL','Albastru Construct Exemplu SRL','Tipar Civic Fictiv SRL','Vector Formare Exemplu SRL'];
const titles=['Platformă de interoperabilitate pentru date urbane','Modernizare rețea Wi-Fi pentru campus public','Servicii de backup și recuperare pentru registre','Portal de servicii digitale pentru cetățeni','Senzori pentru consum energetic','Licențe și suport pentru laboratorul de date','Furnizare produse agricole pentru cantine','Furnizare combustibil pentru flota publică','Echipamente medicale pentru diagnostic','Produse farmaceutice pentru stoc strategic','Lucrări de reparație clădire publică','Servicii de curățenie și igienizare'];
const summaries=['Soluție modulară cu livrare etapizată și criterii măsurabile.','Furnizare și instalare cu instruire și suport inclus.','Servicii recurente cu verificări și raportare lunară.'];
const doc=(name:string,id:string,page:number,complete:boolean,snippet:string) => ({name,complete,source:`fixture://${id}/${name.toLowerCase().replaceAll(' ','-')}`,page,offset:page*117,snippet});
export const demoTenders: Tender[] = titles.map((title,i)=>{const cpv=cpvDomains[i]; const buyer=buyersSeed[i%buyersSeed.length]; const b1=firms[i%firms.length], b2=firms[(i+3)%firms.length]; const decision=i%5===3?'NO-GO':i%3===1?'WATCH':'GO'; const bids=i%4===2?[]:[{firm:b1,price_mdl:Math.round((420000+i*173000)*(.88+(i%3)*.035)),quality:76+(i*7)%21,delivery_days:45+i*11,status:i<6?'În evaluare':'Câștigătoare'},{firm:b2,price_mdl:Math.round((420000+i*173000)*(.94+(i%2)*.02)),quality:72+(i*9)%25,delivery_days:55+i*9,status:i<6?'Depusă':'Respinsă'}]; return {id:`SYN-RO-26-${String(i+1).padStart(3,'0')}`,title,buyer,buyerId:`BUY-SYN-${String(i%8+1).padStart(3,'0')}`,cpv,status:i<6?'Publicată':i<9?'Evaluare':i===9?'Anulată':'Finalizată',decision,deadline:`${18+i} sept 2026`,value_mdl:420000+i*173000,fit:91-i*3,risk:18+(i*7)%67,summary:summaries[i%3],requirements:['Experiență relevantă demonstrată','Plan de livrare și continuitate','Declarație de eligibilitate și conformitate'],documents:[doc('Caiet de sarcini',`syn-${i+1}`,3,true,`Cerința principală pentru ${cpv.code} este descrisă și verificabilă.`),doc('Formular ofertă',`syn-${i+1}`,7,i%4!==3,`Criteriul preț-calitate și documentele obligatorii sunt marcate în fixture.`)],bids,historyNote:i>7?'Istoric sintetic: procedură finalizată sau anulată; cauza este fixture, nu statistică reală.':undefined};});
export const buyers=buyersSeed.map((name,i)=>({id:`BUY-SYN-${String(i+1).padStart(3,'0')}`,name,pattern:i%2?'repetă achiziții de servicii cu termene scurte':'publică loturi recurente cu criterii clare'}));
export const companies=firms.map((name,i)=>({id:`SUP-SYN-${String(i+1).padStart(3,'0')}`,name,wins:(i%4)+1,focus:cpvDomains[i%cpvDomains.length].name}));
export const detailFor=(t:Tender):Detail=>{const avg=t.bids.length?t.bids.reduce((a,b)=>a+b.price_mdl,0)/t.bids.length:t.value_mdl;const discount=Math.round((1-avg/t.value_mdl)*100);const conclusions:Conclusion[]=[{title:'Decizie explicabilă',text:`${t.decision} deoarece fit-ul este ${t.fit}/100, iar riscul este ${t.risk}/100; aceasta este o regulă de prioritizare a fixture-ului.`,source:t.documents[0].source,confidence:'Ridicată'},{title:'Presiune de preț',text:t.bids.length?`Cele ${t.bids.length} oferte sunt în medie cu ${Math.max(0,discount)}% sub bugetul sintetic; compară marja înainte de depunere.`:'Nu există oferte încă; presiunea de preț nu poate fi estimată.',source:t.documents[1].source,confidence:t.bids.length?'Medie':'Limitată'},{title:'Risc operațional',text:t.documents.some(d=>!d.complete)?'Un document este incomplet, iar termenul de clarificări poate scurta pregătirea dosarului.':'Documentele fixture sunt indexate; rămâne de verificat capacitatea de livrare și eligibilitatea.',source:t.documents.find(d=>!d.complete)?.source||t.documents[0].source,confidence:'Medie'}];return {tender:t,checks:t.requirements.map((label,j)=>({label,value:t.documents.every(d=>d.complete)||j===0,note:t.documents.every(d=>d.complete)?'Confirmat în document fixture':'Necesită validare în dosarul furnizorului'})),evidence:t.documents,conclusions};};
export const searchEntities=():EntityResult[]=>[...demoTenders.map(t=>({kind:'Procedură' as const,title:t.title,subtitle:`${t.id} · ${t.buyer}`,tenderId:t.id})),...buyers.map(b=>({kind:'Cumpărător' as const,title:b.name,subtitle:`${b.id} · istoric sintetic`,entityType:'buyer' as const,entityId:b.id})),...companies.map(c=>({kind:'Companie' as const,title:c.name,subtitle:`${c.id} · participări sintetice`,entityType:'company' as const,entityId:c.id}))];
